'use client';

import { useEffect, useState } from 'react';
import saApi from '@/lib/saApi';
import StatusBadge from '@/components/superadmin/StatusBadge';

export default function SecurityLogsPage() {
  const [logs, setLogs] = useState([]); const [severity, setSeverity] = useState(''); const [type, setType] = useState(''); const [restaurant, setRestaurant] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [cursor, setCursor] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async ({ append = false, nextCursor = null } = {}) => { setLoading(true); setError(''); try { const query = new URLSearchParams(); if (severity) query.set('severity', severity); if (type) query.set('type', type); if (restaurant) query.set('restaurant', restaurant); if (from) query.set('from', from); if (to) query.set('to', to); if (nextCursor) query.set('cursor', nextCursor); const result = await saApi.getSecurityLogs(query.toString()); setLogs((current) => append ? [...current, ...(result.logs || [])] : result.logs || []); setCursor(result.nextCursor); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  return <div className="space-y-6"><div><h1 className="text-2xl font-black">Security events</h1><p className="mt-1 text-sm text-sa-500">Authentication, authorization, tenant-isolation, session, CSRF, OAuth, and suspicious access signals.</p></div><form onSubmit={(event) => { event.preventDefault(); load(); }} className="grid gap-2 rounded-2xl border border-sa-800 bg-sa-900 p-4 sm:grid-cols-2 xl:grid-cols-6"><select value={severity} onChange={(event) => setSeverity(event.target.value)} className="rounded-xl border border-sa-700 bg-sa-950 px-3 py-2"><option value="">All severities</option><option>INFO</option><option>WARNING</option><option>CRITICAL</option></select><input value={type} onChange={(event) => setType(event.target.value)} placeholder="Filter event type…" className="rounded-xl border border-sa-700 bg-sa-950 px-3 py-2" /><input value={restaurant} onChange={(event) => setRestaurant(event.target.value)} placeholder="Restaurant name or slug" className="rounded-xl border border-sa-700 bg-sa-950 px-3 py-2" /><input aria-label="From date" type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="rounded-xl border border-sa-700 bg-sa-950 px-3 py-2" /><input aria-label="To date" type="date" value={to} onChange={(event) => setTo(event.target.value)} className="rounded-xl border border-sa-700 bg-sa-950 px-3 py-2" /><button disabled={loading} className="rounded-xl bg-brand-500 px-4 py-2 font-black disabled:opacity-50 text-sa-950">Apply</button></form>{error && <div className="rounded-xl border border-red-800 bg-red-500/10 p-4 text-red-300">{error}</div>}<div className="overflow-hidden rounded-2xl border border-sa-800 bg-sa-900"><div className="divide-y divide-sa-800">{logs.map((item) => <div key={item.id} className="grid gap-3 p-4 text-sm lg:grid-cols-[240px_1fr_180px]"><div><div className="font-bold">{item.type}</div><div className="text-xs text-sa-500">{item.ipAddress || 'IP unavailable'}</div></div><div>{item.message}<div className="mt-1 text-xs text-sa-500">User {item.userId || 'unknown'} · tenant {item.restaurantId || 'none'}</div></div><div className="flex items-center justify-between gap-2"><StatusBadge status={item.severity === 'CRITICAL' ? 'FAILED' : item.severity} /><span className="text-xs text-sa-500">{new Date(item.createdAt).toLocaleString()}</span></div></div>)}</div>{!logs.length && !loading && <div className="p-12 text-center text-sa-500">No security events match these filters.</div>}{cursor && <button disabled={loading} onClick={() => load({ append: true, nextCursor: cursor })} className="w-full border-t border-sa-800 p-3 text-sm font-bold text-orange-400 disabled:opacity-50">{loading ? 'Loading…' : 'Load more'}</button>}</div></div>;
}
